[project]
name = "composer-toolchain"
version = "0.1.0"
description = "Set of score-centric tools for music composers."
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
  "pydantic>=2.11.4",
  "rich",
  "questionary",
  "typer",
  "loguru",
  "backoff",
  "music21",
  "converter21",
  "pydub",
  "abctoolkit",
  "openai>=1.51.0",
]

[dependency-groups]
mcp = [
  "openai-agents",
  "fastmcp",
]
dev = [
  "pytest",
  "pytest-asyncio",
  "pytest-datadir",
  "basedpyright",
  "ruff",
  "black",
]

[project.scripts]
media-reconcile = "composer_toolchain.cli:root_app"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.pyright]
pythonVersion = "3.12"
include = ["src", "scripts"]
typeCheckingMode = "standard"
enableTypeIgnoreComments = false
deprecateTypingAliases = false
reportUnnecessaryTypeIgnoreComment = "error"
strictListInference = true
strictDictionaryInference = true
strictSetInference = true

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["B009", "B010"]
