[build-system]
requires = [
    "uv-build>=0.9.6,<0.10.0",
]
build-backend = "uv_build"

[project]
name = "composer-toolchain"
version = "0.1.0"
description = "Set of score-centric tools for music composers."
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
  "pydantic>=2.11.4",
  "rich",
  "typer",
  "loguru",
  "backoff",
  "music21",
  "converter21",
  "pydub",
  "abctoolkit",
]

[project.optional-dependencies]
mcp = [
  "openai-agents",
  "fastmcp",
]
dev = [
  "pytest",
  "pytest-asyncio",
  "black",
  "pyright",
]

[dependency-groups]
dev = [
  "pytest",
  "pytest-asyncio",
  "black",
  "pyright",
]

[tool.pyright]
include = ["src", "tests"]
exclude = ["**/node_modules", "**/__pycache__", "lib"]
venvPath = "."
venv = ".venv"
extraPaths = [
  ".venv/lib/python3.11/site-packages",
]

[tool.uv.pip]
prerelease = "allow"

# [tool.uv.extra-build-dependencies]
# pkuseg = ["numpy"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
